---
title: "Datos Electorales Distrito 18"
subtitle: "Caracterización por Comuna"
author: ""
output:
  xaringan::moon_reader:
    css: [xaringan-themer.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
    includes:
      in_header: header.html
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(fig.showtext = TRUE)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)

theme_xaringan(
  text_color = "#333f48",
  background_color = "#FFFFFF",
  accent_color = "#900DA4",
  text_font = "Fira Mono",
  text_font_use_google = TRUE,
  title_font = "Fira Sans Condensed",
  title_font_use_google = TRUE
)

style_mono_accent(
  #base_color = "#bf5700",
  extra_fonts = list(google_font("Fira Sans","200","300","400","500","600"),
                     google_font("Fira Sans Condensed")),
  base_color = "#333f48",
  header_font_google = google_font("Yanone Kaffeesatz","200","300","400","500","600","700"),
  text_font_google   = google_font("Roboto", "300", "300i","400","500"),
  code_font_google   = google_font("Fira Mono"),
  text_bold_color = "#333f48",
  text_font_size = "110%",
  colors = c(
    red = "#f34213",
    purple = "#900DA4",
    orange = "#ff8811",
    green = "#136f63",
    white = "#FFFFFF"),
  extra_css = list(
    ".remark-slide table" = list("display" = "table",
                   "width" = "80%",
                   "text-align" = "left"),
    ".remark-slide-number" = list("display" = "none"),
    ".strong" = list("font-weight" = "400"),
    ".big" = list("font-size" = "350%",
                     "font-family" = "Yanone Kaffeesatz",
                     "font-weight"="400"),
    ".small" = list("font-size" = "80%"),
    ".source" = list("color" = "#8c8c8c",
                     "font-size" = "80%"),
    ".remark-slide table td#highlight" = list("background-color" = "#eee1f0",
                                  "color" = "#900DA4",
                                  "font-weight" = "500"),
   # ".remark-slide table thead th" = list(),
    ".title-slide h1" = list("font-weight" = "500"),
    ".title-slide h2" = list("font-weight" = "400",
                             "font-size" =  "170%"),
    ".title-slide h3" = list("font-family" = "Roboto",
                             "font-size" = "100%",
                             "font-weight" = "200"),
    ".center2" = list("margin" = "0",
                      "position" = "absolute",
                      "top" = "50%",
                      "left" = "50%",
                      "-ms-transform" = "translate(-50%, -50%)",
                      "transform" = "translate(-50%, -50%)"),
    ".section-title h1" = list("color" = "#FFFFFF",
                               "font-size" = "2.3em",
                               "line-height" = "1.3"),
    ".medium" = list("font-size" = "1.4em"),
    ".sp-after-half" = list("margin-bottom" = "0.7em !important"),
    ".box-1,.box-1a,.box-1b,.section-title-1" = list("background-color" = "#0D0887"),
    ".box-2,.box-2a,.box-2b,.section-title-2" = list("background-color" = "#5601A4"),
    ".box-3,.box-3a,.box-3b,.section-title-3" = list("background-color" = "#900DA4"),
    ".box-4,.box-4a,.box-4b,.section-title-4" = list("background-color" = "#BF3984"),
    ".box-5,.box-5a,.box-5b,.section-title-5" = list("background-color" = "#E16462"),
    ".box-6,.box-6a,.box-6b,.section-title-6" = list("background-color" = "#F89441"),
    ".box-7,.box-7a,.box-7b,.section-title-7" = list("background-color" = "#FCCE25"),
    ".box-7, .box-6, .box-5, .box-4, .box-3, .box-2, .box-1" = list("color" = "#FFFFFF",
                                                                    "margin" = "0em auto",
                                                                    "overflow" = "hidden",
                                                                    "padding" = "0.4em 0.4em",
                                                                    "font-weight" = "600",
                                                                    "font-size" = "31px",
                                                                    "display" = "table",
                                                                    "text-align" = "center",
                                                                    "font-family" = "Fira Sans"),
    ".box-7a, .box-6a, .box-5a, .box-4a, .box-3a, .box-2a, .box-1a" = list("color" = "#FFFFFF",
                                                                          "left" = "0px",
                                                                          "overflow" = "hidden",
                                                                      "padding" = "0.4em 0.4em",
                                                                      "font-weight" = "600",
                                                                      "font-size" = "25px",
                                                                      "display" = "table",
                                                                      "text-align" = "center",
                                                                      "font-family" = "Fira Sans"),
       ".box-7b, .box-6b, .box-5b, .box-4b, .box-3b, .box-2b, .box-1b" = list("color" = "#FFFFFF",
                                                                          "left" = "0px",
                                                                          "overflow" = "hidden",
                                                                      "padding" = "0.4em 0.4em",
                                                                      "font-weight" = "600",
                                                                      "font-size" = "25px",
                                                                      "display" = "table",
                                                                      "text-align" = "left",
                                                                      "font-family" = "Fira Sans")
  )
)

#,"li" = list("font-size" = "150%")
#    "li" = list("font-size" = "110%"),
#    "ul" = list("font-size" = "110%"),
#color palette
#5601A4
#900DA4
#F89441
#FCCE25
```

# Caracterización por Edad Distrito 18

```{r edad, fig.height=6, fig.width=8, fig.align='center', dev='svg', echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(RColorBrewer)
library(firasans)
library(shades)
library(colorspace)
library(htmltools)
library(ggplot2)
library(ggmap)
library(wesanderson)
library(scales)
library(grid)
library(gridExtra)
library(gtable)
library(hrbrthemes)
library(stringr)
library(leaflet)
library(stringr) 
library(gtools)

#hrbrthemes::update_geom_font_defaults(family=font_rc)

##### Data del censo
d_census = read.csv("https://raw.githubusercontent.com/maibennett/d18/main/data/censo/Cantidad-de-Personas-por-Sexo-y-Edad_d18.csv")

edad_out = c("0 a 4", "5 a 9", "10 a 14", "15 a 19","Total Comunal")
d_census = d_census[!(d_census$edad %in% edad_out),]

edad_old = c("80 a 84","85 a 89","90 a 94", "95 a 99", "100 o mas")
d_census$edad[d_census$edad %in% edad_old] = "80 o mas"

d_census = rename(d_census,rango_edad = edad)
d_census$data = "Censo 2017"

d_census$nom_comuna = str_to_title(d_census$nom_comuna)

##### Data del servel
d_inscritos = read.csv("https://raw.githubusercontent.com/maibennett/d18/main/data/servel/padron2020.csv")

d_inscritos_sum = d_inscritos %>% count(comuna, rango_edad)
names(d_inscritos_sum) = c("nom_comuna","rango_edad","total")
d_inscritos_sum$data = "Inscritos 2020"

d_votantes2017 = read.csv("https://raw.githubusercontent.com/maibennett/d18/main/data/servel/votantes2017.csv")

d_inscritos2017_sum = d_votantes2017 %>% count(comuna, rango_edad)
names(d_inscritos2017_sum) = c("nom_comuna","rango_edad","total")
d_inscritos2017_sum$data = "Inscritos 2017"

d_votantes2017_sum = d_votantes2017[d_votantes2017$sufragio=="sufragó",] %>% count(comuna, rango_edad)
names(d_votantes2017_sum) = c("nom_comuna","rango_edad","total")
d_votantes2017_sum$data = "Votantes 2017"


d_aux = smartbind(d_inscritos2017_sum,d_votantes2017_sum,d_inscritos_sum)
#d_aux = d_aux %>% add_row(data = "Censo 2017", rango_edad = "18 a 19", total = NA)
d_aux$rango_edad = factor(d_aux$rango_edad)

d_aux = d_aux %>% group_by(data,rango_edad) %>% 
  summarise(total = sum(total))

d_aux$data = factor(d_aux$data, levels = c("Inscritos 2017","Votantes 2017","Inscritos 2020"))

ggplot(d_aux, aes(x = rango_edad, y = total, color = data, fill=data), 
       fill="white") +
  geom_bar(stat = "identity", lwd=1.5,position=position_dodge(), width = 0.8)+
  scale_color_manual(values=c("#900DA4","#F89441","#FCCE25")) + 
  scale_fill_manual(values=c(alpha("#900DA4",0.5),alpha("#F89441",0.5),
                             alpha("#FCCE25",0.5))) +

  theme_bw()+
  theme_ipsum_fsc(plot_title_face = "bold") + #plain 
  xlab("Edad (años)") + ylab("Num. inscritos/votantes")+ggtitle("Inscritos y votantes por grupo etario - D18")+
  theme(plot.margin=unit(c(1,1,1.5,1.2),"cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.line = element_line(colour = "dark grey"))+
  
  theme(axis.title.x = element_text(size=16),#margin = margin(t = 10, r = 0, b = 0, l = 0)),
        axis.text.x = element_text(size=10, angle = 45,
                                   hjust=1,vjust=1,margin=margin(0.1,0,0,0)),
        axis.title.y = element_text(size=16),#margin = margin(t = 0, r = 10, b = 0, l = 0)),
        axis.text.y = element_text(size=10),legend.position=c(0.95,1),
        legend.title = element_blank(),
        legend.text = element_text(size=10),
        legend.background = element_rect(fill="white",colour ="white"),
        title = element_text(size=14))

```
---
# Distribución de partidos políticos
```{r pp1, fig.height=6, fig.width=8, fig.align='center', dev='svg', echo=FALSE, warning=FALSE, message=FALSE}

d_votantes2017$partido = str_to_title(d_votantes2017$partido)

#Unidad constituyente reúne a los miembros de Convergencia Progresista (PR, PS, PPD), la Democracia Cristiana, el PRO y Ciudadanos
#De esta lista "Amplitud" es derecha, "Progresista" y "Todos" es concerta, y todo lo demás es delictivo izquierda FA+PC+Locos Addams

d_votantes2017$partido_6 = NA
izq_extra = c("Andha Chile","Comunista De Chile","Ecologista Verde",
              "Humanista","Igualdad","Izquierda Ciudadana De Chile",
              "Mas-Region","Pais","Poder Ciudadano","Regionalista Independiente",
              "Revolucion Democratica","Democracia Regional Patagonica")

centro_indep = c("Liberal De Chile","Ciudadanos")

concertacion = c("Democrata Cristiano","Por La Democracia","Radical Socialdemocrata",
                 "Socialista De Chile","Progresista","Todos")

centro_derecha = c("Renovacion Nacional","Evolucion Politica","Amplitud")
  
derecha = c("Union Democrata Independiente","Union Patriotica")

d_votantes2017$partido_6[d_votantes2017$partido %in% izq_extra] = "Izquierda"
d_votantes2017$partido_6[d_votantes2017$partido %in% concertacion] = "Ex-Concertacion"
d_votantes2017$partido_6[d_votantes2017$partido %in% centro_indep] = "Centro-Indep"
d_votantes2017$partido_6[d_votantes2017$partido %in% centro_derecha] = "Centro-Derecha"
d_votantes2017$partido_6[d_votantes2017$partido %in% derecha] = "Derecha"
d_votantes2017$partido_6[d_votantes2017$partido %in% "Sin Partido"] = "Sin Partido"

d_votantes2017$data = "Inscritos 2017"

d_partidos2017_sum = d_votantes2017 %>% count(data,partido_6)

d_partidos2017_voto_sum = d_votantes2017[d_votantes2017$sufragio=="sufragó",] %>% count(data,partido_6)
d_partidos2017_voto_sum$data = "Votantes 2017"

d_partidos2017_sum = d_partidos2017_sum %>% add_row(d_partidos2017_voto_sum)

d_partidos2017_sum$partido_6 = factor(d_partidos2017_sum$partido_6,
                                      levels = c("Sin Partido","Izquierda","Ex-Concertacion",
                                                 "Centro-Indep","Centro-Derecha","Derecha"))

ggplot(d_partidos2017_sum, aes(x = partido_6, y = n, color = partido_6, fill=partido_6), 
       fill="white") +
  geom_bar(stat = "identity", lwd=1.5,position=position_dodge(), width = 0.8)+
  scale_color_manual(values=c("#0D0887","#5601A4","#900DA4",
                              "#BF3984","#F89441","#FCCE25")) + 
  scale_fill_manual(values=c(alpha("#0D0887",0.5),alpha("#5601A4",0.5),
                             alpha("#900DA4",0.5), alpha("#BF3984",0.5),
                             alpha("#F89441",0.5),alpha("#FCCE25",0.5))) +

  theme_bw()+
  theme_ipsum_fsc(plot_title_face = "bold") + #plain 
  xlab("Tendencia") + ylab("Num. inscritos/votantes")+ggtitle("Inscritos y votantes por tendencia de partido - D18")+
  theme(plot.margin=unit(c(1,1,1.5,1.2),"cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.line = element_line(colour = "dark grey"))+
  
  theme(axis.title.x = element_text(size=16),#margin = margin(t = 10, r = 0, b = 0, l = 0)),
        axis.text.x = element_text(size=10, angle = 45,
                                   hjust=1,vjust=1,margin=margin(0.1,0,0,0)),
        axis.title.y = element_text(size=16),#margin = margin(t = 0, r = 10, b = 0, l = 0)),
        axis.text.y = element_text(size=10),legend.position=c(0.95,1),
        legend.title = element_blank(),
        legend.text = element_text(size=10),
        legend.background = element_rect(fill="white",colour ="white"),
        title = element_text(size=14)) + facet_grid(cols=vars(factor(data)))

```
---
# Distribución de partidos políticos: Solo inscritos
```{r pp2, fig.height=6, fig.width=8, fig.align='center', dev='svg', echo=FALSE, warning=FALSE, message=FALSE}


ggplot(d_partidos2017_sum[d_partidos2017_sum$partido_6!="Sin Partido",], 
       aes(x = partido_6, y = n, color = partido_6, fill=partido_6), 
       fill="white") +
  geom_bar(stat = "identity", lwd=1.5,position=position_dodge(), width = 0.8)+
  scale_color_manual(values=c("#5601A4","#900DA4",
                              "#BF3984","#F89441","#FCCE25")) + 
  scale_fill_manual(values=c(alpha("#5601A4",0.5),
                             alpha("#900DA4",0.5), alpha("#BF3984",0.5),
                             alpha("#F89441",0.5),alpha("#FCCE25",0.5))) +

  theme_bw()+
  theme_ipsum_fsc(plot_title_face = "bold") + #plain 
  xlab("Tendencia") + ylab("Num. inscritos/votantes")+ggtitle("Inscritos y votantes por tendencia de partido - D18")+
  theme(plot.margin=unit(c(1,1,1.5,1.2),"cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.line = element_line(colour = "dark grey"))+
  
  theme(axis.title.x = element_text(size=16),#margin = margin(t = 10, r = 0, b = 0, l = 0)),
        axis.text.x = element_text(size=10, angle = 45,
                                   hjust=1,vjust=1,margin=margin(0.1,0,0,0)),
        axis.title.y = element_text(size=16),#margin = margin(t = 0, r = 10, b = 0, l = 0)),
        axis.text.y = element_text(size=10),legend.position=c(0.95,1),
        legend.title = element_blank(),
        legend.text = element_text(size=10),
        legend.background = element_rect(fill="white",colour ="white"),
        title = element_text(size=14)) + facet_grid(cols=vars(factor(data)))

```
